language: java
jdk: openjdk11
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - |
    task=$(git diff --name-only $TRAVIS_BRANCH...HEAD | awk -F/ '{print $(NF-1)}' | sort -u | grep task)
    echo $task
    count=`echo $task | wc -w`
    if [ "$count" == "0" ];
    then
      echo "Nothing to check"
      exit 1
    fi
    if [ $count != 1 ];
    then
      echo "Only single task is allowed"
      exit 1
    fi
    echo "Checking $task"
    cmd="./gradlew :$task:clean :$task:check"
    $cmd

